import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { Download, Copy, RefreshCw } from "lucide-react";
import { AdminLayout } from "@/components/admin/AdminLayout";
import { BRAND } from "@/config/brand";
import { LOCATIONS, PRIMARY_LOCATION } from "@/config/locations";
import { SERVICES } from "@/config/services";
import { AI_PROVIDER } from "@/config/aiProvider";
import { MAP_CONFIG } from "@/config/maps";
import { useQuery } from "@tanstack/react-query";

const AdminExport = () => {
  const [exportFormat, setExportFormat] = useState<"json" | "markdown">("json");

  // Fetch counts
  const { data: aiContentCount, isLoading: loadingAI } = useQuery({
    queryKey: ["export-ai-content-count"],
    queryFn: async () => {
      const { count } = await supabase
        .from("ai_content")
        .select("*", { count: "exact", head: true });
      return count || 0;
    },
  });

  const { data: blogPostCount, isLoading: loadingBlog } = useQuery({
    queryKey: ["export-blog-count"],
    queryFn: async () => {
      const { count } = await supabase
        .from("blog_posts")
        .select("*", { count: "exact", head: true });
      return count || 0;
    },
  });

  const { data: leadsCount, isLoading: loadingLeads } = useQuery({
    queryKey: ["export-leads-count"],
    queryFn: async () => {
      const { count } = await supabase
        .from("leads")
        .select("*", { count: "exact", head: true });
      return count || 0;
    },
  });

  const generateJSONSnapshot = () => {
    return JSON.stringify({
      exportedAt: new Date().toISOString(),
      brand: BRAND,
      primaryLocation: PRIMARY_LOCATION,
      locations: LOCATIONS,
      services: SERVICES.map(s => ({
        slug: s.slug,
        name: s.name,
        shortLabel: s.shortLabel,
        description: s.description,
        icon: s.icon,
        subServices: s.subServices || [],
      })),
      aiProvider: AI_PROVIDER,
      mapConfig: MAP_CONFIG,
      stats: {
        aiContentEntries: aiContentCount || 0,
        blogPosts: blogPostCount || 0,
        leads: leadsCount || 0,
        totalLocations: LOCATIONS.length,
        totalServices: SERVICES.length,
        totalSubServices: SERVICES.reduce((acc, s) => acc + (s.subServices?.length || 0), 0),
      },
    }, null, 2);
  };

  const generateMarkdownSnapshot = () => {
    const subServicesCount = SERVICES.reduce((acc, s) => acc + (s.subServices?.length || 0), 0);
    
    return `# Configuration Snapshot

**Exported:** ${new Date().toISOString()}

---

## Brand Configuration

| Field | Value |
|-------|-------|
| Brand Name | ${BRAND.brandName} |
| Domain | ${BRAND.domain} |
| Phone | ${BRAND.phone} |
| Email | ${BRAND.email} |
| Address | ${BRAND.addressLine1}, ${BRAND.postcode} |
| Primary Location | ${BRAND.primaryLocation} |
| Service Area | ${BRAND.serviceAreaLabel} |

---

## Locations (${LOCATIONS.length})

| Name | Slug | Region | Coordinates |
|------|------|--------|-------------|
${LOCATIONS.map(l => `| ${l.name} | ${l.slug} | ${l.countyOrRegion || '-'} | ${l.latitude}, ${l.longitude} |`).join('\n')}

---

## Services (${SERVICES.length})

${SERVICES.map(s => `### ${s.icon} ${s.name}
- **Slug:** ${s.slug}
- **Short Label:** ${s.shortLabel}
- **Description:** ${s.description}
${s.subServices?.length ? `- **Sub-services:** ${s.subServices.map(sub => sub.name).join(', ')}` : ''}
`).join('\n')}

---

## Statistics

| Metric | Count |
|--------|-------|
| AI Content Entries | ${aiContentCount || 0} |
| Blog Posts | ${blogPostCount || 0} |
| Leads Collected | ${leadsCount || 0} |
| Total Locations | ${LOCATIONS.length} |
| Total Services | ${SERVICES.length} |
| Total Sub-Services | ${subServicesCount} |

---

## Technical Configuration

- **AI Provider:** ${AI_PROVIDER}
- **Map Provider:** ${MAP_CONFIG.provider}
- **Map Zoom:** ${MAP_CONFIG.defaultZoom}

---

*Generated by Admin Export Tool*
`;
  };

  const getSnapshot = () => {
    return exportFormat === "json" ? generateJSONSnapshot() : generateMarkdownSnapshot();
  };

  const downloadSnapshot = () => {
    const content = getSnapshot();
    const extension = exportFormat === "json" ? "json" : "md";
    const mimeType = exportFormat === "json" ? "application/json" : "text/markdown";
    
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `config-snapshot-${Date.now()}.${extension}`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Snapshot downloaded");
  };

  const copySnapshot = () => {
    navigator.clipboard.writeText(getSnapshot());
    toast.success("Snapshot copied to clipboard");
  };

  const isLoading = loadingAI || loadingBlog || loadingLeads;

  return (
    <AdminLayout 
      title="Export Snapshot" 
      description="Export configuration and statistics for documentation or handover"
    >
      {/* Format Selection */}
      <div className="mb-6 flex gap-4">
        <Button
          variant={exportFormat === "json" ? "default" : "outline"}
          onClick={() => setExportFormat("json")}
        >
          JSON Format
        </Button>
        <Button
          variant={exportFormat === "markdown" ? "default" : "outline"}
          onClick={() => setExportFormat("markdown")}
        >
          Markdown Format
        </Button>
      </div>

      {/* Quick Stats */}
      <div className="grid md:grid-cols-4 gap-4 mb-6">
        <div className="p-4 bg-card rounded-lg">
          <p className="text-sm text-muted-foreground">AI Content</p>
          <p className="text-2xl font-bold">
            {isLoading ? <RefreshCw className="h-5 w-5 animate-spin" /> : aiContentCount}
          </p>
        </div>
        <div className="p-4 bg-card rounded-lg">
          <p className="text-sm text-muted-foreground">Blog Posts</p>
          <p className="text-2xl font-bold">
            {isLoading ? <RefreshCw className="h-5 w-5 animate-spin" /> : blogPostCount}
          </p>
        </div>
        <div className="p-4 bg-card rounded-lg">
          <p className="text-sm text-muted-foreground">Leads</p>
          <p className="text-2xl font-bold">
            {isLoading ? <RefreshCw className="h-5 w-5 animate-spin" /> : leadsCount}
          </p>
        </div>
        <div className="p-4 bg-card rounded-lg">
          <p className="text-sm text-muted-foreground">Locations</p>
          <p className="text-2xl font-bold">{LOCATIONS.length}</p>
        </div>
      </div>

      {/* Preview */}
      <div className="bg-card p-6 rounded-xl mb-6">
        <h2 className="text-xl font-bold mb-4">Preview</h2>
        <Textarea
          value={getSnapshot()}
          readOnly
          className="font-mono text-sm h-96"
        />
      </div>

      {/* Actions */}
      <div className="flex gap-4">
        <Button onClick={downloadSnapshot}>
          <Download className="h-4 w-4 mr-2" />
          Download {exportFormat.toUpperCase()}
        </Button>
        <Button variant="outline" onClick={copySnapshot}>
          <Copy className="h-4 w-4 mr-2" />
          Copy to Clipboard
        </Button>
      </div>

      {/* Usage Notes */}
      <div className="mt-8 p-4 bg-muted rounded-lg">
        <h3 className="font-semibold mb-2">Usage</h3>
        <ul className="text-sm text-muted-foreground space-y-1">
          <li>• Use <strong>JSON</strong> for programmatic imports or backup</li>
          <li>• Use <strong>Markdown</strong> for documentation or buyer handover</li>
          <li>• This snapshot includes all configuration but no sensitive data (API keys)</li>
          <li>• Lead data count is shown but actual lead details are not exported here</li>
        </ul>
      </div>
    </AdminLayout>
  );
};

export default AdminExport;
